### ISSUE TITLE
Error when clicking some of the generated products in the UI.

### ISSUE THREAD

**Issue by DavidKelemen** [Ucommercenet/Ucommerce-Seeder#2]
`[NotSupportedException: Could not find a control factory which supports data type 'bit'. Please register a new IControlFactory in DataTypes.config which supports the data type.]
   UCommerce.Presentation.Web.Controls.PropertyControlFactory.GetControl(IProperty property) +423
   UCommerce.Web.UI.UCommerce.Controls.PropertyEditor.OnInit(EventArgs e) +188
   System.Web.UI.Control.InitRecursive(Control namingContainer) +454
   System.Web.UI.Control.InitRecursive(Control namingContainer) +219
   System.Web.UI.Control.InitRecursive(Control namingContainer) +219
   System.Web.UI.Control.AddedControl(Control control, Int32 index) +239
   UCommerce.Web.UI.Controls.PropertyList.InitializePropertyList() +2153
   System.Web.UI.Control.InitRecursive(Control namingContainer) +454
   System.Web.UI.Control.AddedControl(Control control, Int32 index) +239
   UCommerce.Web.UI.Catalog.EditProductBaseProperties.AddPropertiesToPanel() +240
   System.Web.UI.Control.OnInit(EventArgs e) +99
   System.Web.UI.Control.InitRecursive(Control namingContainer) +454
   System.Web.UI.Control.InitRecursive(Control namingContainer) +219
   System.Web.UI.Control.InitRecursive(Control namingContainer) +219
   System.Web.UI.Control.AddedControl(Control control, Int32 index) +239
   UCommerce.Web.UI.UCommerce.MasterPages.UCommerceAdmin.OnInit(EventArgs e) +463
   System.Web.UI.Control.InitRecursive(Control namingContainer) +454
   System.Web.UI.Control.InitRecursive(Control namingContainer) +219
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1760`

Seems like there's a datatype created with a wrong editor ('bit'). That is the datatype in SQL but not in Ucommerce.

**Comment by skovsboll** [comment]
It's true that the seeder creates new data types:

![Skærmbillede 2020-09-07 kl  15 35 14](https://user-images.githubusercontent.com/531026/92393159-bd464280-f11f-11ea-978d-066e190df7a6.png)

I'd argue this is something we want to happen.

Creating a new DataType by hand would have the same effect in the legacy UI: If there's no IControlFactory to support it, it throws. 

IMO this should be handled better by the UI, perhaps by guiding the user to the documentation. I don't want to cripple this seeding task just because the UI can't handle it.

**Comment by nebse** [comment]
@DavidKelemen is this still relevant?
